CREATE DATABASE IF NOT EXISTS dashboard;

USE dashboard;

CREATE TABLE IF NOT EXISTS top (
    ID INT PRIMARY KEY auto_increment,
    METRIC VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    EXPOSED DOUBLE NOT NULL,
    CONTROL DOUBLE NOT NULL,
    UPLIFT DOUBLE NOT NULL,
    PCT_UPLIFT DOUBLE NOT NULL
);

LOAD DATA LOCAL INFILE './data/top.csv'
INTO TABLE top
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(METRIC, PRODUCT, EXPOSED, CONTROL, UPLIFT, PCT_UPLIFT);


CREATE TABLE IF NOT EXISTS weekly (
    ID INT PRIMARY KEY auto_increment,
    PRODUCT VARCHAR(255) NOT NULL,
    WEEK_COMMENCING DATE NOT NULL,
    EXPOSED DOUBLE NOT NULL,
    CONTROL DOUBLE NOT NULL
);

LOAD DATA LOCAL INFILE './data/weekly.csv'
INTO TABLE weekly
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS   
(PRODUCT, WEEK_COMMENCING, EXPOSED, CONTROL);
